# Generated by Django 3.1.5 on 2021-03-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mensaje_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_mensaje', to='login_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario_mensaje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_comentario', to='muro_app.mensajes')),
                ('comentario_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_comentario', to='login_app.usuario')),
            ],
        ),
    ]
