# Generated by Django 3.1.5 on 2021-03-18 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('muro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario_usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_comentario', to='login_app.usuario'),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje_usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_mensaje', to='login_app.usuario'),
        ),
    ]
